#!/usr/bin/env python3
"""
gen_files.py -- generate hdl/sine_qrom.v and the simulation stimulus.

  python3 gen_files.py            # writes ../hdl/sine_qrom.v and stimulus.hex

Stimulus (390,625 S/s, 12-bit XADC codes around mid-scale 2048):
  * 24.8 kHz 200-baud MSK, amplitude 100 counts       (an "NLK" signal, ch0)
  * 21.4 kHz pure tone,    amplitude  20 counts       (ch1, exact amplitude check)
  * 23.6 kHz pure tone,    amplitude 300 counts       (400 Hz below the 24.0 kHz
                                                        channel: adjacent-signal test)
  * uniform integer noise -3..+3 counts
  * a clipping burst at samples 50000..50007 (five 4095s then three 0s)
"""
import math
import os
import random

from vlf_model import qrom_table, FS_NOM

HERE = os.path.dirname(os.path.abspath(__file__))
N_SAMPLES = 90_000
CLIP_AT = 50_000


def write_rom(path):
    t = qrom_table()
    lines = [
        "`timescale 1ns / 1ps",
        "//-----------------------------------------------------------------------------",
        "// sine_qrom.v -- quarter-wave sine table, two read ports (generated by",
        "//                sim/gen_files.py -- do not edit by hand)",
        "//",
        "// T[i] = round(32767 * sin(2*pi*(i + 0.5) / 4096)), i = 0..1023",
        "// The half-step phase offset makes the quadrant symmetry exact, so a",
        "// 12-bit phase index gets a full sine from this quarter table:",
        "//   q0: T[a]   q1: T[~a]   q2: -T[a]   q3: -T[~a]",
        "// Registered outputs (one clock latency); infers one RAMB18 as a ROM.",
        "//-----------------------------------------------------------------------------",
        "module sine_qrom (",
        "    input  wire        clk,",
        "    input  wire        en,",
        "    input  wire [9:0]  addr_a,",
        "    input  wire [9:0]  addr_b,",
        "    output reg  [14:0] data_a,",
        "    output reg  [14:0] data_b",
        ");",
        "    (* rom_style = \"block\" *) reg [14:0] rom [0:1023];",
        "",
        "    initial begin",
    ]
    for i, v in enumerate(t):
        lines.append(f"        rom[{i:4d}] = 15'd{v};")
    lines += [
        "    end",
        "",
        "    always @(posedge clk) begin",
        "        if (en) begin",
        "            data_a <= rom[addr_a];",
        "            data_b <= rom[addr_b];",
        "        end",
        "    end",
        "",
        "endmodule",
        "",
    ]
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines))


def make_stimulus(msk=True, tone1=True, tone2=True, noise=True, clip=True, quantize=True):
    """Return the stimulus. With quantize=False, returns float samples (no
    rounding, no clamping) so check_vlf.py can study single components; the
    random sequence is the same whichever parts are switched on."""
    rng = random.Random(19)          # experiment #19
    fs = float(FS_NOM)
    # 200-baud MSK: frequency f0 +/- 50 Hz, continuous phase
    f0, baud, a_msk = 24_800.0, 200.0, 100.0
    sps = fs / baud                  # 1953.125 samples per bit
    dev = baud / 4.0                 # +/- 50 Hz
    bits = [rng.choice((-1, 1)) for _ in range(int(N_SAMPLES / sps) + 2)]
    out = []
    ph_msk = 0.0
    for n in range(N_SAMPLES):
        b = bits[int(n / sps)]
        s = a_msk * math.cos(ph_msk) if msk else 0.0
        ph_msk += 2.0 * math.pi * (f0 + b * dev) / fs
        if tone1:
            s += 20.0 * math.cos(2.0 * math.pi * 21_400.0 * n / fs + 0.7)
        if tone2:
            s += 300.0 * math.cos(2.0 * math.pi * 23_600.0 * n / fs + 1.9)
        e = rng.randint(-3, 3)
        if noise:
            s += e
        if quantize:
            c = int(round(2048.0 + s))
            out.append(min(4095, max(0, c)))
        else:
            out.append(2048.0 + s)
    if clip:
        for k in range(8):
            out[CLIP_AT + k] = 4095 if k < 5 else 0
    return out


if __name__ == "__main__":
    rom_path = os.path.normpath(os.path.join(HERE, "..", "hdl", "sine_qrom.v"))
    write_rom(rom_path)
    codes = make_stimulus()
    with open(os.path.join(HERE, "stimulus.hex"), "w", newline="\n") as f:
        for c in codes:
            f.write(f"{c:03x}\n")
    print(f"wrote {rom_path}")
    print(f"wrote stimulus.hex: {len(codes)} samples, min {min(codes)}, max {max(codes)}")
